### ISSUE TITLE
Release robolectric-bazel for Robolectric 4.8.2

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric-bazel#30]
See https://github.com/robolectric/robolectric/releases/tag/robolectric-4.8.2.

**Comment by utzcoz** [comment]
Hi @Bencodes could you help to release a new version of robolectric-bazel?

**Comment by Bencodes** [comment]
> Hi @Bencodes could you help to release a new version of robolectric-bazel?

Yeah i'll cut a new release today.

**Comment by Bencodes** [comment]
@utzcoz did new instrumented Android jars get pushed for this?

**Comment by hoisie** [comment]
@Bencodes nope, no new preinstrumented jars

**Comment by Bencodes** [comment]
The 4.8.2 release has been cut https://github.com/robolectric/robolectric-bazel/releases/tag/4.8.2

**Comment by utzcoz** [comment]
@Bencodes Thanks.

**Comment by utzcoz** [comment]
@Bencodes Maybe we need to update documentation too. It's not a big deal.

**Comment by Bencodes** [comment]
Updated the README as well. Thanks for catching that.

**Comment by utzcoz** [comment]
@Bencodes Thanks for your work.
