### ISSUE TITLE
Release robolectric-bazel 4.10

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric-bazel#61]
I think the robolectric-bazel is ready for 4.10. Because this release contains the part for BCR, @Bencodes maybe it needs you to help do this release. Thanks.

**Comment by Bencodes** [comment]
@utzcoz I was following up with the Bazel team about Bzlmod support for Android before I cut the release. It would appear that Bzlmod doesn't _fully_ support Android yet.

I'll cut a release anyways and just leave the Bzlmod support out of the readme until i'm able to confirm everything on the Android side.

**Comment by Bencodes** [comment]
https://github.com/bazelbuild/bazel-central-registry/pull/576 BCR pull request is up. I'm going to wait to confirm on the Android side that everything works before I update the readme.

**Comment by utzcoz** [comment]
@Bencodes It's fine. We can do what we can do and update the documentation when Bazelmod is ready for Android projects.

**Comment by utzcoz** [comment]
I updated the release note to contain full 4.10 commits at https://github.com/robolectric/robolectric-bazel/releases/tag/4.10.
