### ISSUE TITLE
How to avoid missing updating Robolectric version for README?

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric-bazel#67]
For example, we have released this project for Robolectric 4.10.3, but the README still uses Robolectric 4.10.1.

**Comment by Bencodes** [comment]
This repo would benefit from a Github Workflow automation that cuts the release and updates the README with the correct versions. Something like https://github.com/keith/buildifier-prebuilt/blob/main/.github/workflows/create_release.yml

**Comment by utzcoz** [comment]
@Bencodes It sounds great. Could you help support it?

**Comment by Bencodes** [comment]
The instructions have been moved to the release page so this shouldn't be an issue anymore.
